### ISSUE TITLE
Transparent images

### ISSUE THREAD

**Issue by bradydowling** [esimov/triangle#12]
Is there a way to make images with transparent elements or a transparent background?

**Comment by esimov** [comment]
@bradydowling what do you mean by transparent elements or transparent background? Can you give me an example? Eventual a sketch or something to understand it better.

**Comment by bradydowling** [comment]
Ya, for example, here's an image I created with primitive:

![black-stroke-bezier](https://user-images.githubusercontent.com/6668371/78571692-7e206800-77f4-11ea-9824-59e62fc25fc7.png)

Note the transparent background. Primitive handles this by allowing the user to [specify a background color](https://github.com/fogleman/primitive/issues/54#issuecomment-346067124), including the alpha. And in this next one, many of the shapes have only partial opacity.

![black-stroke-rotellipse](https://user-images.githubusercontent.com/6668371/78572066-fd15a080-77f4-11ea-846e-04327f0111e0.png)

**Comment by esimov** [comment]
I will check and if it's possible I'll integrate.

**Comment by esimov** [comment]
I was thinking about the possible solutions, but one more thing I want to clarify: since this tool is based on the delaunay triangulation this means that the triangles are computed by calculating the average cell color. Because in certain cases we don't have an image with a fully opaque or transparent backround this means we need to detect the most dominant color as a background color and apply the desired color as a background. 

Can you show me what you got and what is the desired effect?

**Comment by bradydowling** [comment]
Forgive me if I'm misunderstanding how this works but I'll give it my best shot.

> Because in certain cases we don't have an image with a fully opaque or transparent background

Do you just mean the background could be semi-transparent (e.g. alpha of 0.5)? What if you allowed the user to manually specify the background color so detection doesn't need to happen? Then each triangle can be placed atop that background.

> Can you show me what you got and what is the desired effect?

I believe you're looking for the source image for both of those images I produced above. This is it:

![black-stroke-transparent-cropped](https://user-images.githubusercontent.com/6668371/78666485-694fdd00-78a5-11ea-91bf-27215dc82129.png)

Then with that, I specified the base background color for the image that is produced.

**Comment by esimov** [comment]
I'll look into it to see if it's possible without major changes.

**Comment by esimov** [comment]
@bradydowling I've integrated the requested features. Please pull out the latest code and give it a try. As an example here is how it looks like. I have also updated the documentation. 

![triangle](https://user-images.githubusercontent.com/883386/79323725-406bbf80-7f17-11ea-8ce1-f524f0e81dd5.png)

**Comment by bradydowling** [comment]
Awesome! It looks like it's working with some images. This one doesn't seem to be working. Here's the image:

![black-stroke-transparent-cropped](https://user-images.githubusercontent.com/6668371/79342830-a0ed0380-7efb-11ea-83a0-b4e6b8971864.png)

And here's the command I'm running as well as the output:
```
$ triangle -in originals/black-stroke-transparent-cropped.png -out black-stroke-triangle-app.png -bg=#00000000
Generating triangulated image... \
Generated in: 0.13s
Total number of 2 triangles generated out of 0 points
Saved on: black-stroke-triangle-app.png ✓
```

I get the same thing when passing `-bg=#ffffff00` and the resulting image is purely transparent. I wonder if this is an issue specific to pure black.

**Comment by esimov** [comment]
I was searching for the reason, but haven't found yet, but definitely it's related to how the image is encoded, because if i'm re-saving in Photoshop then it's working. I'm still investigating.

**Comment by bradydowling** [comment]
Very interesting. I had tried a couple things troubleshooting but had
considered that, good thought.

**Comment by esimov** [comment]
I've resolved the issue you reported. The reason was the swapped color channels: ABGR instead of RGBA. Please check it and let me know if it's working for you. I have also created a new release. 

![triangle2](https://user-images.githubusercontent.com/883386/79733579-05de9a00-82fe-11ea-9ea1-6ea0ccdf564d.png)

**Comment by bradydowling** [comment]
That looks more blobby than triangulated. I guess should just fix the source image I have and then rerun it to see if that will produce a nice image. After pulling it's producing the same thing that you shared above. I believe you can resolve this now, thank you for your work on it! 🙏

**Comment by esimov** [comment]
This has to do with the type of the underlying image and since it has an uniform single color the tool fills up the produced inner triangles with the same color. You can prove yourself if you are running the following command:

```bash
triangle -in ~/Desktop/79342830-a0ed0380-7efb-11ea-83a0-b4e6b8971864.png -out ~/Desktop/triangle.png -bg="#ff000000" -stroke=0 -wireframe=0 -gray=0 -sobel=5 -blur=4 -max=1500 -wireframe=2 -stroke=1
```
This is the output it generates:

![triangle2](https://user-images.githubusercontent.com/883386/79758778-80231480-8326-11ea-8f8e-3ed9a823a8b6.png)

**Comment by esimov** [comment]
If you don't mind I'll close this issue. You can reopen it at any time if that's the case.
