### ISSUE TITLE
Backward compatible?

### ISSUE THREAD

**Issue by pjebs** [esimov/triangle#24]
It's the new API backward compatible?

Also, if I have a 2x2 image and I set maxpoints to 1, what does that mean?

**Comment by esimov** [comment]
It's not 100% backward compatible, but it has been marked with a new major Semver version change, so it shouldn't be a problem of updating the existing projects with the new API changes.

**Comment by pjebs** [comment]
My understanding is Go mod uses semantic versioning and any backward incompatible changes must be marked as next major version (i.e. v2)

**Comment by pjebs** [comment]
https://go.dev/doc/modules/version-numbers

**Comment by esimov** [comment]
You are right. It was my misconception that it should work with a new minor version update. Unfortunately I didn't followed the semver rules adapted to the Go module versioning. I have updated the code and module directives to v2, so now it should be working by tagging to v2, even if it's not backward compatible. I had to make this compromise because I wasn't satisfied with the API design.

**Comment by pjebs** [comment]
Is the theoretical maximum for maxPoints equal to the image's height*width?

**Comment by esimov** [comment]
Theoretically yes, but it depends from the other parameters.
